# Generated by Django 2.2 on 2019-04-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortenurl',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
