# Generated by Django 2.2 on 2019-04-29 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20190429_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shortenurl',
            old_name='date',
            new_name='add_date',
        ),
    ]
