# Generated by Django 2.2 on 2019-04-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0006_auto_20190429_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenurl',
            name='id',
        ),
        migrations.AlterField(
            model_name='shortenurl',
            name='short_url',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
